### ISSUE TITLE
โอนเงินใส่ข้อความแล้วไม่ขึ้นครับ

### ISSUE THREAD

**Issue by saeeiabpinglinenotify** [likecyber/php-truewallet-class#4]
ตอนโอนเงินเวลาใส่ข้อความแล้วมันไม่บันทึก พอจะแก้ไขได้ไหมครับ

**Comment by likecyber** [comment]
ตัวผมยังหาวิธีแก้ไม่ได้ครับ ถ้าแก้ไขได้แล้วจะมีการอัพเดทอีกทีครับ

**Comment by saeeiabpinglinenotify** [comment]
> ตัวผมยังหาวิธีแก้ไม่ได้ครับ ถ้าแก้ไขได้แล้วจะมีการอัพเดทอีกทีครับ

ขอบคุณมากๆครับ

**Comment by nuattawoot-sa** [comment]
เช็คเลขอ้างอิง true wallet อันนี้ตัอง call ที่ api ไหนครับ

**Comment by likecyber** [comment]
สวัสดีครับ ทางคุณอาจจะแก้ไขปัญหานี้ไปก่อนหน้านี้แล้วนะครับ
แต่ตอนนี้ ผมได้ทำการอัพเดท Function ConfirmTransferP2P()
ให้สามารถใช้ $personal_message ได้อย่างถูกต้องแล้วครับ
สามารถตรวจสอบได้จาก TrueWallet.class.php เวอร์ชั่น 2.1.0 เป็นต้นไปครับ

ขอบคุณครับ
