### ISSUE TITLE
เช็คเลขอ้างอิง true wallet อันนี้ตัอง call ที่ api ไหนครับ

### ISSUE THREAD

**Issue by nuattawoot-sa** [likecyber/php-truewallet-class#5]
เช็คเลขอ้างอิง true wallet อันนี้ตัอง call ที่ api ไหนครับ

**Comment by likecyber** [comment]
สวัสดีครับ ทางคุณอาจจะแก้ไขปัญหานี้ไปก่อนหน้านี้แล้วนะครับ
แต่ตอนนี้ ผมได้ทำการอัพเดทเพิ่ม Function GetDetailTransferP2P()
ทำให้สามารถตรวจสอบรายละเอียดหลังดำเนินการ P2P Transfer ได้ครับ
สามารถตรวจสอบได้จาก TrueWallet.class.php เวอร์ชั่น 2.1.0 เป็นต้นไปครับ

ขอบคุณครับ
